// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktyzwazachlsqpvlnvfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0eXp3YXphY2hsc3FwdmxudmZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2ODkyOTUsImV4cCI6MjA3NDI2NTI5NX0.eG2lTcihT34UWdjQ_Vd2WxlUwMMfIQa2G8ms5Lmguxg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});